## roles/ansible-role-nfs-server/tasks/main.yml
## Role main file
# vim:ft=yaml.ansible:
---
## Initialise distribution-specific variables
- name: "Include OS-specific vars"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "RHEL 7 specific overrides"
  include_vars: RedHat-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7

- name: "Fedora specific overrides"
  include_vars: Fedora.yml
  when: ansible_distribution == "Fedora"

- name: "Arch specific overrides"
  include_vars: Arch Linux.yml
  when: "'Arch' in ansible_distribution"

## Setup and install
- include_tasks: setup-{{ ansible_os_family }}.yml
  
- name: Ensure directories to export exists
  file: 
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }} "
  notify: Restart NFS

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copy
  notify: Restart NFS

- name: Restart NFS immediately if exports are updated.
  service: "name={{ nfs_server_daemon }} state=restarted"
  when: nfs_exports_copy.changed

- name: Ensure NFS is running.
  service: "name={{ nfs_server_daemon }} state=restarted enabled=yes"
  when: nfs_exports|length
...
