## roles/ansible-role-nfs-server/handlers/main.yml
# Handlers for the role
# vim:ft=yaml.ansible:
---
- name: Restart NFS
  service: "name={{ nfs_server_daemon }} state=restarted"
  when: nfs_exports|length
...

